apiVersion: v1
kind: Service 
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:  #traffic will go to app mentioned below
    app: myapp
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port